[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[build]
  node_version = "14.17.0"
  publish = "dist"  # Ensure to specify the publish directory
  command = "npm run build"  # Specify the build command
